listhings = {

nationalities : [
  // SOURCE:
  // http://www.guavastudios.com/downloads/nationalities/nationalities.csv
  "Afghan","Albanian","Algerian","American","Andorran","Angolan","Antiguans",
  "Argentinean","Armenian","Australian","Austrian","Azerbaijani","Bahamian",
  "Bahraini","Bangladeshi","Barbadian","Barbudans","Batswana","Belarusian",
  "Belgian","Belizean","Beninese","Bhutanese","Bolivian","Bosnian","Brazilian",
  "British","Bruneian","Bulgarian","Burkinabe","Burmese","Burundian",
  "Cambodian","Cameroonian","Canadian","Cape Verdean","Central African",
  "Chadian","Chilean","Chinese","Colombian","Comoran","Congolese","Costa Rican",
  "Croatian","Cuban","Cypriot","Czech","Danish","Djibouti","Dominican","Dutch",
  "East Timorese","Ecuadorean","Egyptian","Emirian","Equatorial Guinean",
  "Eritrean","Estonian","Ethiopian","Fijian","Filipino","Finnish","French",
  "Gabonese","Gambian","Georgian","German","Ghanaian","Greek","Grenadian",
  "Guatemalan","Guinea-Bissauan","Guinean","Guyanese","Haitian","Herzegovinian",
  "Honduran","Hungarian","Icelander","Indian","Indonesian","Iranian","Iraqi",
  "Irish","Israeli","Italian","Ivorian","Jamaican","Japanese","Jordanian",
  "Kazakhstani","Kenyan","Kittian and Nevisian","Kuwaiti","Kyrgyz","Laotian",
  "Latvian","Lebanese","Liberian","Libyan","Liechtensteiner","Lithuanian",
  "Luxembourger","Macedonian","Malagasy","Malawian","Malaysian","Maldivan",
  "Malian","Maltese","Marshallese","Mauritanian","Mauritian","Mexican",
  "Micronesian","Moldovan","Monacan","Mongolian","Moroccan","Mosotho",
  "Motswana","Mozambican","Namibian","Nauruan","Nepalese","Netherlander",
  "New Zealander","Ni-Vanuatu","Nicaraguan","Nigerian","Nigerien",
  "North Korean","Northern Irish","Norwegian","Omani","Pakistani","Palauan",
  "Panamanian","Papua New Guinean","Paraguayan","Peruvian","Polish",
  "Portuguese","Qatari","Romanian","Russian","Rwandan","Saint Lucian",
  "Salvadoran","Samoan","San Marinese","Sao Tomean","Saudi","Scottish",
  "Senegalese","Serbian","Seychellois","Sierra Leonean","Singaporean",
  "Slovakian","Slovenian","Solomon Islander","Somali","South African",
  "South Korean","Spanish","Sri Lankan","Sudanese","Surinamer","Swazi",
  "Swedish","Swiss","Syrian","Taiwanese","Tajik","Tanzanian","Thai","Togolese",
  "Tongan","Trinidadian or Tobagonian","Tunisian","Turkish","Tuvaluan",
  "Ugandan","Ukrainian","Uruguayan","Uzbekistani","Venezuelan","Vietnamese",
],

countries : [
  // SOURCE
  // http://www.guavastudios.com/downloads/countries/countries.csv
  "Åland Islands","Afghanistan","Albania","Algeria","American Samoa","Andorra",
  "Angola","Anguilla","Antarctica","Antigua And Barbuda","Argentina","Armenia",
  "Aruba","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh",
  "Barbados","Belarus","Belgium","Belize","Benin","Bermuda","Bhutan","Bolivia",
  "Bosnia And Herzegovina","Botswana","Bouvet Island","Brazil",
  "British Indian Ocean Territory","Brunei Darussalam","Bulgaria",
  "Burkina Faso","Burundi","Cambodia","Cameroon","Canada","Cape Verde",
  "Cayman Islands","Central African Republic","Chad","Chile","China",
  "Christmas Island","Cocos (keeling) Islands","Colombia","Comoros","Congo",
  "Congo","The Democratic Republic Of The","Cook Islands","Costa Rica",
  "Croatia","Cuba","Cyprus","Czech Republic","CÔte D'ivoire","Denmark",
  "Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador",
  "Equatorial Guinea","Eritrea","Estonia","Ethiopia",
  "Falkland Islands (malvinas)","Faroe Islands","Fiji","Finland","France",
  "French Guiana","French Polynesia","French Southern Territories","Gabon",
  "Gambia","Georgia","Germany","Ghana","Gibraltar","Greece","Greenland",
  "Grenada","Guadeloupe","Guam","Guatemala","Guernsey","Guinea","Guinea-bissau",
  "Guyana","Haiti","Heard Island And Mcdonald Islands","Honduras","Hong Kong",
  "Hungary","Iceland","India","Indonesia","Iran","Islamic Republic Of","Iraq",
  "Ireland","Isle Of Man","Israel","Italy","Jamaica","Japan","Jersey","Jordan",
  "Kazakhstan","Kenya","Kiribati","Korea","Democratic People's Republic Of",
  "Korea","Republic Of","Kuwait","Kyrgyzstan",
  "Lao People's Democratic Republic","Latvia","Lebanon","Lesotho","Liberia",
  "Libyan Arab Jamahiriya","Liechtenstein","Lithuania","Luxembourg","Macao",
  "Macedonia","The Former Yugoslav Republic Of","Madagascar","Malawi",
  "Malaysia","Maldives","Mali","Malta","Marshall Islands","Martinique",
  "Mauritania","Mauritius","Mayotte","Mexico","Micronesia",
  "Federated States Of","Moldova","Monaco","Mongolia","Montenegro","Montserrat",
  "Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands",
  "Netherlands Antilles","New Caledonia","New Zealand","Nicaragua","Niger",
  "Nigeria","Niue","Norfolk Island","Northern Mariana Islands","Norway","Oman",
  "Pakistan","Palau","Palestinian Territory","Occupied","Panama",
  "Papua New Guinea","Paraguay","Peru","Philippines","Pitcairn","Poland",
  "Portugal","Puerto Rico","Qatar","Romania","Russian Federation","Rwanda",
  "RÉunion","Saint BarthÉlemy","Saint Helena","Saint Kitts And Nevis",
  "Saint Lucia","Saint Martin","Saint Pierre And Miquelon",
  "Saint Vincent And The Grenadines","Samoa","San Marino",
  "Sao Tome And Principe","Saudi Arabia","Senegal","Serbia","Seychelles",
  "Sierra Leone","Singapore","Slovakia","Slovenia","Solomon Islands","Somalia",
  "South Africa","South Georgia And The South Sandwich Islands","Spain",
  "Sri Lanka","Sudan","Suriname","Svalbard And Jan Mayen","Swaziland","Sweden",
  "Switzerland","Syrian Arab Republic","Taiwan","Province Of China",
  "Tajikistan","Tanzania","United Republic Of","Thailand","Timor-leste","Togo",
  "Tokelau","Tonga","Trinidad And Tobago","Tunisia","Turkey","Turkmenistan",
  "Turks And Caicos Islands","Tuvalu","Uganda","Ukraine","United Arab Emirates",
  "United Kingdom","United States","United States Minor Outlying Islands",
  "Uruguay","Uzbekistan","Vanuatu","Vatican City State","Venezuela","Viet Nam",
  "Virgin Islands","British","Virgin Islands","U.s.","Wallis And Futuna",
  "Western Sahara","Yemen","Zambia","Zimbabwe"
],

religions : [
  // SOURCE
  // http://www.guavastudios.com/downloads/religions/major-religions.csv
  "African Traditional & Diasporic","Agnostic","Atheist","Baha'i","Buddhism",
  "Cao Dai","Chinese traditional religion","Christianity","Hinduism","Islam",
  "Jainism","Juche","Judaism","Neo-Paganism","Nonreligious","Rastafarianism",
  "Secular","Shinto","Sikhism","Spiritism","Tenrikyo","Unitarian-Universalism",
  "Zoroastrianism","primal-indigenous"
],

languages : [
  "Akan","Amharic","Arabic","Assamese","Awadhi","Azerbaijani","Balochi",
  "Belarusian","Bengali","Bhojpuri","Burmese","Cantonese","Cebuano","Chewa",
  "Chhattisgarhi","Chittagonian","Czech","Deccan","Dhundhari","Dutch","English",
  "French","Fula","Gan","German","Greek","Gujarati","Haitian Creole","Hakka",
  "Haryanvi","Hausa","Hiligaynon","Hindi","Hmong","Hungarian","Igbo","Ilokano",
  "Italian","Japanese","Javanese","Jin","Kannada","Kazakh","Khmer",
  "Kinyarwanda","Kirundi","Konkani","Korean","Kurdish","Madurese","Magahi",
  "Maithili","Malagasy","Malay/Indonesian","Malayalam","Mandarin","Marathi",
  "Marwari","Min Bei","Min Dong","Min Nan","Mossi","Nepali","Oriya","Oromo",
  "Pashto","Persian","Polish","Portuguese","Punjabi","Quechua","Romanian",
  "Russian","Saraiki","Serbo-Croatian","Shona","Sindhi","Sinhalese","Somali",
  "Spanish","Sundanese","Swahili","Swedish","Sylheti","Tagalog","Tamil",
  "Telugu","Thai","Turkish","Ukrainian","Urdu","Uyghur","Uzbek","Vietnamese",
  "Wu","Xhosa","Xiang","Yoruba","Zhuang","Zulu"
],

languagesBySpeakers : [
  "Mandarin","Spanish","English","Hindi","Arabic","Portuguese","Bengali",
  "Russian","Japanese","Punjabi","German","Javanese","Wu","Malay/Indonesian",
  "Telugu","Vietnamese","Korean","French","Marathi","Tamil","Urdu","Persian",
  "Turkish","Italian","Cantonese","Thai","Gujarati","Jin","Min Nan","Polish",
  "Pashto","Kannada","Xiang","Malayalam","Sundanese","Hausa","Oriya","Burmese",
  "Hakka","Ukrainian","Bhojpuri","Tagalog","Yoruba","Maithili","Swahili",
  "Uzbek","Sindhi","Amharic","Fula","Romanian","Oromo","Igbo","Azerbaijani",
  "Awadhi","Gan","Cebuano","Dutch","Kurdish","Serbo-Croatian","Malagasy",
  "Saraiki","Nepali","Sinhalese","Chittagonian","Zhuang","Khmer","Assamese",
  "Madurese","Somali","Marwari","Magahi","Haryanvi","Hungarian","Chhattisgarhi",
  "Greek","Chewa","Deccan","Akan","Kazakh","Min Bei","Sylheti","Zulu","Czech",
  "Kinyarwanda","Dhundhari","Haitian Creole","Min Dong","Ilokano","Quechua",
  "Kirundi","Swedish","Hmong","Shona","Uyghur","Hiligaynon","Mossi","Xhosa",
  "Belarusian","Balochi","Konkani"
],

races : [
  "African","Arab","Brazilian","British","Chinese","Egyptian","Filipino",
  "French","German","Hispanic","Indian","Italian","Japanese","Korean","Malay",
  "Scottish","Pakistani","Persian","Portugese","Russian","Spanish","Sri Lankan",
  "Thai","Turkish","Other"
]

};
